language: cpp
compiler: gcc
install:
- sudo apt-get -y install build-essential checkinstall cmake pkg-config yasm unzip
- sudo apt-get -y install libtiff4-dev libjpeg-dev libjasper-dev
- sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev libxine-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libv4l-dev
- sudo apt-get install python-dev python-numpy
- sudo apt-get install libqt4-dev libgtk2.0-dev
- git clone https://github.com/rodrigosiqueira/Sacai.git
- cd Sacai/others/
- unzip opencv-2.4.10.zip
- cd opencv-2.4.10/
- mkdir build/
- cd build/
- cmake -D WITH_QT=ON -D WITH_XINE=ON -D WITH_OPENGL=ON -D WITH_TBB=ON -D BUILD_EXAMPLES=ON ..
- make
- sudo make install
- sudo echo "/usr/local/lib" >> /etc/ld.so.conf
- sudo ldconfig
- export LD_LIBRARY_PATH=:/usr/local/lib
- cd ../../
- wget http://googletest.googlecode.com/files/gtest-1.7.0.zip
- unzip gtest-1.7.0.zip
- cd gtest-1.7.0
- mkdir mybuild
- cd mybuild
- cmake -DBUILD_SHARED_LIBS=ON -Dgtest_build_samples=ON -G"Unix Makefiles" ..
- make
- sudo cp lib*.so /usr/lib 
- cd ..
- sudo cp -a include/gtest /usr/include
- cd ..
- rm gtest-1.7.0.zip
- cd ../
script:
- make clean
- make
